### ISSUE TITLE
CdConsoleCommand

### ISSUE THREAD

**Issue by otter18** [otter18/csharp-hse#1]
Файл: [CdConsoleCommand.cs](https://github.com/otter18/csharp-hse/blob/sem-2022-10-12/sem-2022-10-12/ConsoleCommands/CdConsoleCommand.cs)

- Синтаксис команды: `cd <path>`
- Примерный функционал:
    - [x]  path может быть как абсолютным путей, так и относительным
    - [x] поддержка `cd ..`
    - [x] проверка на существования пути, иначе сообщение об ошибке
    - [x] нельзя подниматься выше `ConsoleEngine.RootDir` (Используйте `ConsoleEngine.IsInRoot`)
    - [x] `cd /` переходит в `ConsoleEngine.RootDir` [[comment]](https://github.com/otter18/csharp-hse/issues/1#issuecomment-1280648054)

**Comment by otter18** [comment]
- [ ] А можешь сделать пж, чтобы `cd /` переходило в `RootDir`

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/46843878/196156258-73ab99cc-3281-45e8-95f3-67bcd4caccbb.png">

**Comment by ghost** [comment]
Я попробую

**Comment by ghost** [comment]
Сделал

**Comment by ghost** [comment]
Я переделал на выбрасывание исключений.
