### ISSUE TITLE
Вопрос о проверке на выход из корневой директории

### ISSUE THREAD

**Issue by ghost** [otter18/csharp-hse#8]
Я видел, что такая проверка есть не только у меня. Может, стоит как-то вынести эту логику и повторно использовать (DRY-принцип)?

**Comment by otter18** [comment]
Разумно. Я подумаю

**Comment by ghost** [comment]
Можно организовать какой-то класс со всеми нужными проверками, либо все запихнуть в ConsoleEngine. Второй вариант хуже, т.к. нарушаем принцип единственной ответсвенности (single reponsibility).
